version: 0.1

env:
  variables:
    NAME: "plugins-welcome"
    VERSION: "v0.0.1"

phases:
  install:
    commands:
      - echo Build started on `date`
  pre_build:
    commands:
      - "echo Building $NAME-$VERSION"
  build:
    commands:
      - npm install
  post_build:
    commands:
      - echo Build completed on `date`
